<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>MyCPlus.Sorting.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/MergeSort/MergeSort.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../expected/MergeSort.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
